### ISSUE TITLE
how to load resolvers ?

### ISSUE THREAD

**Issue by veeramarni** [creditkarma/graphql-loader#6]
This module helps a ton. How to load resolvers in the same fashion?

**Comment by nnance** [comment]
sorry for the slow response.  still need help with this?

**Comment by veeramarni** [comment]
Well, I was wondering whether there is a way to load resolvers in the similar fashion?

**Comment by jakelacey2012** [comment]
@veeramarni 

This may help https://www.npmjs.com/package/glob

An example would be something like this,
```javascript
import glob from 'glob';

const resolverFilenames = glob.sync('./src/resolvers/*.js');

```
This will return an array of filenames which match the pattern. You will need to construct the full path for the next step.

Once you've figured that out.

you can do this.

```javascript

import { merge } from 'lodash';

let resolvers;

// some loop going through all of the full paths in the array....

const resolvers = merge(require(`${fullPath}`), resolvers);

//....end loop

export default resolvers; /// will be an object with all the resolvers merged....

```

Now this solution assumes one thing an that `require(`${fullPath}`)` is exporting an object.

I hope this helps.

**Comment by veeramarni** [comment]
Thanks, we have already [figured this out](https://github.com/cdmbase/fullstack-pro/blob/master/packages/sample-graphql-schema/src/index.ts#L29).
