### ISSUE TITLE
Love it.. now webpack?!

### ISSUE THREAD

**Issue by orefalo** [creditkarma/graphql-loader#7]
Can't get this guy to work with webpack.

please help

**Comment by nnance** [comment]
Sorry for such a slow response but can you give me a better example of how your trying to get this to work?

**Comment by rwoody** [comment]
The naming of the package is similar to those of Webpack loaders which can be confusing for those who don't read the readme 😄

You could possibly use this as the basis for a Webpack loader which allows importing (and subsequent merging) of schemas when Webpack is used as a bundler for server/backend files.

**Comment by orefalo** [comment]
Took me some time to remember the context ;-)

thank you @rwoody , this explains it all
