### ISSUE TITLE
Any way to get the client schema?

### ISSUE THREAD

**Issue by advance512** [creditkarma/graphql-loader#9]
I mean, the output of [this](http://graphql.org/graphql-js/utilities/#buildclientschema) after converted to string via printSchema.

**Comment by nnance** [comment]
Do you still need help with this?

**Comment by advance512** [comment]
Yes, I do. I do it manually now, running an introspection schema and then storing the output somewhere.

I want to do it dynamically, from the service itself, and to get a simple string representation. 

Suggestions?

**Comment by nnance** [comment]
```js
import { buildClientSchema, introspectionQuery } from 'graphql'
const schema = buildClientSchema(introspectionQuery)
```

Hopefully this helps

**Comment by advance512** [comment]
This is not converted to a string which I can use, which was the point. I want to get this string into a variable.

**Comment by advance512** [comment]
Any update on this? How can I convert it to a string that I can output as simple text in an HTTP request?
